version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "weekly"
    time: "09:00"
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions"
  # Workflow files stored in the
  # default location of `.github/workflows`
  directory: "/"
  schedule:
    interval: "weekly"
    time: "09:00"
