spring:
  datasource:
    port: 11112
    url: jdbc:h2:tcp://localhost:${spring.datasource.port}/mem:test;MODE=ORACLE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  security:
    user:
      name: sa
      password: sa

server:
  port: 11110

ssh:
  port: 2000
  timeouts:
    auth: 600000
    idle: 600000
  credentials:
    user: ${spring.security.user.name}
    password: ${spring.security.user.password}
    key: 'classpath:/ssh/publicKey.pem'
